### ISSUE TITLE
Setup GitHub Actions For Builds and Deployments

### ISSUE THREAD

**Issue by khalidabuhakmeh** [Eptagone/Vite.AspNetCore#8]
👋 Hi @Eptagone 

I wrote a blog post about publishing NuGet packages using git tags and GitHub Actions. You should consider adding it to this project.

https://khalidabuhakmeh.com/a-dotnet-five-guide-from-idea-to-nuget-package

Either way, no pressure :)

**Comment by divyeshio** [comment]
I want to work on this. Can you assign it to me?

**Comment by Eptagone** [comment]
Hi @divyeshio. Of course. Thx

**Comment by Eptagone** [comment]
Thanks @divyeshio.
I also updated the working directories, and I don't know what the MinVer dependency is supposed to do, but I removed it because it made package versions always 0.0.0-alpha.
Everything seems to be working now. Thank you very much for your support of this package.

**Comment by Eptagone** [comment]
Thanks @divyeshio and @khalidabuhakmeh.
I also updated the working directories, and I don't know what the MinVer dependency is supposed to do, but I removed it because it made package versions always 0.0.0-alpha.
Everything seems to be working now. Thank you very much for your support of this package.
